### ISSUE TITLE
latest travis build of develop can not deploy to AWS 

### ISSUE THREAD

**Issue by necampanini** [necampanini/never-a-bad#16]
Whole log is here: https://s3.amazonaws.com/archive.travis-ci.org/jobs/46661857/log.txt

but it looks like **Aws Secret Key does not match Access Key Id, Stopping Deploy
failed to deploy** is the relevant part. This wasn't an issue with the first builds. 

If I remember correctly we put something relating to AWS keys in some file, I'll go through the older stuff and see if I can find it.

**Comment by necampanini** [comment]
So .travis.yml had the secret access keys and what not, and this file did not change from merging branches. I'll dig around in the AWS Console stuff, but I'm not exactly sure what I'm looking for or what to change.

**Comment by jmcampanini** [comment]
Most likely you have to regenerate the secret key because you moved the repos.

Try doing those steps over and see if it works.

**Comment by necampanini** [comment]
Made a new key, that error is gone, but is replaced with something I can't decipher outright. Something about noMethodError and rjust. I remember rjust from awhile back, but that wasn't an issue at all after that. 

https://api.travis-ci.org/jobs/46669308/log.txt?deansi=true for full log again.

**Comment by jmcampanini** [comment]
```
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.9/lib/dpl/provider/s3.rb:27:in `check_auth': undefined method `rjust' for nil:NilClass (NoMethodError)
```

makes me think it's an auth issue.

do you have a PR for the changes to the `.travis.yml` file that is causing this? we should keep the comments about it on that PR... don't be afraid to start a PR for a single file...

**Comment by necampanini** [comment]
fixed, replaced they keys, removed SECRET ACCESS KEY or something.
